### ISSUE TITLE
Make this robust in the face of more packages

### ISSUE THREAD

**Issue by simonw** [simonw/download-esm#2]
So far I've tested this on exactly one package: [@observablehq/plot](https://www.npmjs.com/package/@observablehq/plot).

It would be good to test this on some other packages too! Help very much appreciated here.

Any packages that don't work can be used to expand the test suite. It's all in triple-string-literals in https://github.com/simonw/download-esm/blob/0.1a0/tests/test_download_esm.py at the moment, but it would make sense to turn those HTTPX fixtures into actual files on disk as it expands.

**Comment by simonw** [comment]
It works with Preact!

Fetch `preact` and `htm`:
```
download-esm htm
download-esm preact
```
Save this as `index.html`:
```html
<script type="module">
import { h, Component, render } from './preact-10-13-2.js';
import htm from './htm-3-1-1.js';

// Initialize htm with Preact
const html = htm.bind(h);

function App (props) {
    return html`<h1>Hello ${props.name}!</h1>`;
}

render(html`<${App} name="World" />`, document.body);
</script>
```
Run `python3 -m http.server` and visit` http://localhost:8000/` and:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/9599/235576010-db2dc01e-3e20-4720-92ba-d0182975cae0.png">

**Comment by simonw** [comment]
Got this error trying to fetch `codemirror`:

```
% download-esm codemirror codemirror
codemirror-6-0-1.js
codemirror-view-6-10-1.js
codemirror-language-6-6-0.js
codemirror-autocomplete-6-6-0.js
codemirror-commands-6-2-3.js
codemirror-state-6-2-0.js
codemirror-lint-6-2-1.js
style-mod-4-0-3.js
w3c-keyname-2-2-6.js
codemirror-search-6-4-0.js
crelt-1-0-5.js
codemirror-view-6-9-5.js
codemirror-view-6-10-1.js
lezer-highlight-1-1-4.js
lezer-common-1-0-2.js
Traceback (most recent call last):
  File "/Users/simon/.local/pipx/venvs/download-esm/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/simon/.local/pipx/venvs/download-esm/lib/python3.11/site-packages/httpcore/backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1263, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1136, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
```
It succeeded when I ran it a second time though.

Adding this `index.html` file worked:

```html
<script type="module">
import {EditorView, basicSetup} from "./codemirror-6-0-1.js"

let editor = new EditorView({
  extensions: [basicSetup],
  parent: document.body
})
</script>
```
<img width="465" alt="image" src="https://user-images.githubusercontent.com/9599/235576449-3f3e81eb-be8c-4c12-826b-cfbb3382cb97.png">

**Comment by simonw** [comment]
Sort of got Monaco working:

    download-esm monaco-editor

<img width="479" alt="image" src="https://user-images.githubusercontent.com/9599/235577133-eb32562a-ab09-4739-9400-bca19bacdca9.png">

```html
<script type="module">
import * as monaco from './monaco-editor-0-37-1.js';

const editor = monaco.editor.create(document.body, {
	value: ['def foo(bar):\n    print("baz")'].join('\n'),
});
editor.getModel().updateOptions({ tabSize: 4 });
</script>
```

One catch: if I try to add syntax highlighting with `language: "python"` I get these errors in the console:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/9599/235577279-551d3c29-e005-487f-b689-acf91c030482.png">

**Comment by simonw** [comment]
Mentioned this in https://simonwillison.net/2023/May/2/download-esm/
